/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdjustmentsRouteImport } from './routes/_authenticated/adjustments'
import { Route as AuthenticatedBodegaRouteImport } from './routes/_authenticated/bodega'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedTiresRouteImport } from './routes/_authenticated/tires'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdjustmentsRoute =
  AuthenticatedAdjustmentsRouteImport.update({
    id: '/adjustments',
    path: '/adjustments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBodegaRoute = AuthenticatedBodegaRouteImport.update({
  id: '/bodega',
  path: '/bodega',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTiresRoute = AuthenticatedTiresRouteImport.update({
  id: '/tires',
  path: '/tires',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/adjustments': typeof AuthenticatedAdjustmentsRoute
  '/bodega': typeof AuthenticatedBodegaRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/store': typeof AuthenticatedStoreRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/tires': typeof AuthenticatedTiresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/adjustments': typeof AuthenticatedAdjustmentsRoute
  '/bodega': typeof AuthenticatedBodegaRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/store': typeof AuthenticatedStoreRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/tires': typeof AuthenticatedTiresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/adjustments': typeof AuthenticatedAdjustmentsRoute
  '/_authenticated/bodega': typeof AuthenticatedBodegaRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/tires': typeof AuthenticatedTiresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/adjustments'
    | '/bodega'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/logs'
    | '/purchases'
    | '/sales'
    | '/staff'
    | '/store'
    | '/suppliers'
    | '/tires'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/adjustments'
    | '/bodega'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/logs'
    | '/purchases'
    | '/sales'
    | '/staff'
    | '/store'
    | '/suppliers'
    | '/tires'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/adjustments'
    | '/_authenticated/bodega'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventory'
    | '/_authenticated/logs'
    | '/_authenticated/purchases'
    | '/_authenticated/sales'
    | '/_authenticated/staff'
    | '/_authenticated/store'
    | '/_authenticated/suppliers'
    | '/_authenticated/tires'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/adjustments': {
      id: '/_authenticated/adjustments'
      path: '/adjustments'
      fullPath: '/adjustments'
      preLoaderRoute: typeof AuthenticatedAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bodega': {
      id: '/_authenticated/bodega'
      path: '/bodega'
      fullPath: '/bodega'
      preLoaderRoute: typeof AuthenticatedBodegaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tires': {
      id: '/_authenticated/tires'
      path: '/tires'
      fullPath: '/tires'
      preLoaderRoute: typeof AuthenticatedTiresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdjustmentsRoute: typeof AuthenticatedAdjustmentsRoute
  AuthenticatedBodegaRoute: typeof AuthenticatedBodegaRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTiresRoute: typeof AuthenticatedTiresRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdjustmentsRoute: AuthenticatedAdjustmentsRoute,
  AuthenticatedBodegaRoute: AuthenticatedBodegaRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTiresRoute: AuthenticatedTiresRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
